version: '2'
services:
  webwiss3n-app:
    image: webwiss3n
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://webwiss3n-mysql:3306/webwiss3n?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://webwiss3n-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://webwiss3n-elasticsearch:9200
    ports:
      - 8080:8080
  webwiss3n-mysql:
    extends:
      file: mysql.yml
      service: webwiss3n-mysql
  webwiss3n-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: webwiss3n-elasticsearch
